# XcodeGen Project Configuration
# Install XcodeGen: brew install xcodegen
# Generate project: xcodegen generate

name: Muze
options:
  bundleIdPrefix: com.muze
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en

settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"
  SWIFT_VERSION: "5.9"

targets:
  Muze:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    
    sources:
      - path: Muze
        excludes:
          - Info.plist
    
    settings:
      base:
        PRODUCT_NAME: Muze
        PRODUCT_BUNDLE_IDENTIFIER: com.muze.app
        INFOPLIST_FILE: Muze/Info.plist
        CODE_SIGN_ENTITLEMENTS: Muze/Muze.entitlements
        DEVELOPMENT_TEAM: ""  # Update this with your team ID
        CODE_SIGN_STYLE: automatic
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"  # iPhone and iPad
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        ENABLE_BITCODE: NO
        SWIFT_OPTIMIZATION_LEVEL: -Onone
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      
      debug:
        SWIFT_COMPILATION_MODE: incremental
      
      release:
        SWIFT_OPTIMIZATION_LEVEL: -O
        SWIFT_COMPILATION_MODE: wholemodule
    
    entitlements:
      path: Muze/Muze.entitlements
      properties:
        com.apple.developer.icloud-container-identifiers:
          - iCloud.$(CFBundleIdentifier)
        com.apple.developer.ubiquity-container-identifiers:
          - iCloud.$(CFBundleIdentifier)
        com.apple.developer.icloud-services:
          - CloudDocuments
    
    scheme:
      testTargets: []
      gatherCoverageData: false

schemes:
  Muze:
    build:
      targets:
        Muze: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

